stages:
  - test
  - deploy

test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install -r requirements.txt
  - python manage.py test

staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install -r requirements.txt
  - python manage.py startapp
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install -r requirements.txt
  - python manage.py startapp
  only:
  - tags
