# Generated by Django 3.0.3 on 2020-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=3)),
                ('cause_number', models.CharField(max_length=7, unique=True)),
                ('defendant_name', models.CharField(max_length=25)),
                ('defendant_status', models.CharField(max_length=6)),
                ('bail', models.CharField(max_length=6)),
                ('bond_type', models.CharField(blank=True, max_length=1)),
                ('days_old', models.CharField(max_length=15)),
                ('total_settings', models.CharField(blank=True, max_length=3)),
                ('defense_lawyer', models.CharField(blank=True, max_length=25)),
                ('next_setting', models.DateField()),
                ('next_setting_type', models.CharField(max_length=4)),
                ('charge', models.CharField(max_length=25)),
                ('felony_pending', models.BooleanField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
