# Generated by Django 3.0.3 on 2020-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='felony_pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
