# Generated by Django 3.0.3 on 2020-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0002_auto_20200303_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bail',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='defendant_status',
            field=models.CharField(max_length=10),
        ),
    ]
