# Generated by Django 3.0.3 on 2020-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0003_auto_20200304_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id',
        ),
        migrations.AlterField(
            model_name='case',
            name='cause_number',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
