# Generated by Django 3.0.4 on 2020-04-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_pusher', '0002_auto_20200310_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtform',
            options={'verbose_name': 'Court Form'},
        ),
    ]
